### ISSUE TITLE
Error loading 3d model

### ISSUE THREAD

**Issue by spcsmrf** [ProjectInABox/eagle_libraries#1]
Hello, I'm not sure if I'm doing it wrong but when I load the library locally I get this error
![bild](https://user-images.githubusercontent.com/10047177/42152589-dd79dfbc-7de0-11e8-8b81-f040d9aea9d9.png) and if I upload it through library.io I get this on every package 
![bild](https://user-images.githubusercontent.com/10047177/42152621-0080c9f8-7de1-11e8-9b07-1a8a4efe8860.png) so I would like some help on how to fix it or if you could send me the 3d step for TSA12110/BTN_MOMENTARY_SPST-NO_PTH_L12-W12 please, thanks in advance

**Comment by BrianMH** [comment]
library.io currently only supports private libraries for users' managed libraries. That means the models will only be visible to users logged onto the account that created them (in this case, @MrSwirlyEyes).
You will likely have to wait a bit for @MrSwirlyEyes to export it *for you.

**Comment by spcsmrf** [comment]
thanks so much for the quick reply, I hope that library.io is gonna fix that in the future because it would be nice to be able to share 3d libraries

**Comment by MrSwirlyEyes** [comment]
Is the STEP file fine?  When I created the device in EAGLE, I just uploaded the following STEP file.


~MrSwirlyEyes

**Comment by MrSwirlyEyes** [comment]
https://drive.google.com/open?id=1GZerDl-DpP4J8YcJNyDQCp2DPEsdfo1d

**Comment by spcsmrf** [comment]
thanks so much for the quick help, yes the step file worked fine, thanks so so much! 👍
